name: 😊 Deploiment - Laravel CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.5.2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@2.25.1
      with:
        php-version: '8.2' # Remplacer par la version de PHP que vous utilisez
        extensions: bcmath, bz2, calendar, Core, ctype, curl, date, dom, exif, FFI, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, Phar, posix, readline, redis, Reflection, session, shmop, SimpleXML, soap, sockets, sodium, SPL, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib, Zend OPcache
        tools: composer:v2

    - name: Install NPM
      run: |
        sudo apt-get install -y npm
        npm --version
        
    - name: Change to Laravel directory and print
      run: |
        cd InstaRepas
        pwd
        ls -la

    - name: Install Project Dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        npm install
      working-directory: ./InstaRepas

    - name: Build Project
      run: |
        npm run build
      working-directory: ./InstaRepas
        
    - name: Setup SSH and rsync
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Server to Known Hosts
      run: |
        echo '${{ secrets.REMOTE_HOST }} ${{ secrets.REMOTE_HOST_PUBLIC_KEY }}' >> ~/.ssh/known_hosts
      
    - name: Deploy to Server
      run: |
        rsync -r --delete-after --quiet -e 'ssh -p ${{ secrets.REMOTE_PORT }}' $GITHUB_WORKSPACE/InstaRepas/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/html/InstaRepas
