name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "cd /var/www/html/instarepas && composer install --no-dev && npm install --production && npm run production && php artisan migrate --force && sudo systemctl restart apache2"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: /var/www/html/instarepas
        SOURCE: "InstaRepas/InstaRepas/"
