name: Laravel CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.5.2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@2.25.1
      with:
        php-version: '8.2' # Remplacer par la version de PHP que vous utilisez
        extensions: mbstring, mysqli, pdo_sqlite, ctype, json, iconv # Ajouter / Supprimer des extensions PHP au besoin
        tools: composer:v2

    - name: Install NPM
      run: |
        sudo apt-get install -y npm
        npm --version

    - name: Install Project Dependencies
      run: |
        cd InstaRepas
        composer install --no-progress --prefer-dist --optimize-autoloader
        npm install

    - name: Build Project
      run: |
        npm run production
        
    - name: Setup SSH and rsync
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: Deploy to Server
      run: |
        rsync -r --delete-after --quiet -e 'ssh -p 2266' $GITHUB_WORKSPACE/InstaRepas/ ubuntu@151.80.47.41:/var/www/html/InstaRepas
